### ISSUE TITLE
余额宝收益发放的逻辑写反了

### ISSUE THREAD

**Issue by wwwcycycy** [MickLife/KeepAccounts_v2.0#4]
余额宝的收益应该是正的吧～Excel显示出来都是负的了，可以更改一下。
你写的程序很好用。感谢！

**Comment by cangkongman** [comment]
发错了吧，我没有写过余额宝相关的程序。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MickLife/KeepAccounts_v2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 晚上10:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[MickLife/KeepAccounts_v2.0] 余额宝收益发放的逻辑写反了 (Issue #4)





 
余额宝的收益应该是正的吧～Excel显示出来都是负的了，可以更改一下。
 你写的程序很好用。感谢！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MickLife** [comment]
#5 
已修复支付宝理财收支逻辑bug
